/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MainRender {
    }
    interface MessageSegment {
        "firstObject": any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "first-object"?: any;
        "index": number;
        "secondObject": any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "second-object"?: any;
        "segment": { message: string; condition?: string; draggable?: boolean };
        "values": { [key: string]: string };
    }
}
export interface MessageSegmentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMessageSegmentElement;
}
declare global {
    interface HTMLMainRenderElement extends Components.MainRender, HTMLStencilElement {
    }
    var HTMLMainRenderElement: {
        prototype: HTMLMainRenderElement;
        new (): HTMLMainRenderElement;
    };
    interface HTMLMessageSegmentElementEventMap {
        "segmentDragStart": number;
        "segmentDrop": { fromIndex: number; toIndex: number };
        "inputChange": { key: string; value: string };
    }
    interface HTMLMessageSegmentElement extends Components.MessageSegment, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMessageSegmentElementEventMap>(type: K, listener: (this: HTMLMessageSegmentElement, ev: MessageSegmentCustomEvent<HTMLMessageSegmentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMessageSegmentElementEventMap>(type: K, listener: (this: HTMLMessageSegmentElement, ev: MessageSegmentCustomEvent<HTMLMessageSegmentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMessageSegmentElement: {
        prototype: HTMLMessageSegmentElement;
        new (): HTMLMessageSegmentElement;
    };
    interface HTMLElementTagNameMap {
        "main-render": HTMLMainRenderElement;
        "message-segment": HTMLMessageSegmentElement;
    }
}
declare namespace LocalJSX {
    interface MainRender {
    }
    interface MessageSegment {
        "firstObject"?: any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "first-object"?: any;
        "index"?: number;
        "onInputChange"?: (event: MessageSegmentCustomEvent<{ key: string; value: string }>) => void;
        "onSegmentDragStart"?: (event: MessageSegmentCustomEvent<number>) => void;
        "onSegmentDrop"?: (event: MessageSegmentCustomEvent<{ fromIndex: number; toIndex: number }>) => void;
        "secondObject"?: any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "second-object"?: any;
        "segment"?: { message: string; condition?: string; draggable?: boolean };
        "values"?: { [key: string]: string };
    }
    interface IntrinsicElements {
        "main-render": MainRender;
        "message-segment": MessageSegment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "main-render": LocalJSX.MainRender & JSXBase.HTMLAttributes<HTMLMainRenderElement>;
            "message-segment": LocalJSX.MessageSegment & JSXBase.HTMLAttributes<HTMLMessageSegmentElement>;
        }
    }
}
