/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FirstObjectComponent {
        "firstObject": { name: string; refId: number; type: 'claim' | 'normal' | 'promotion'; urgency: 'high' | 'medium' | 'low' };
    }
    interface MainRender {
    }
    interface MessageSegment {
        "firstObject": any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "first-object"?: any;
        "index": number;
        "secondObject": any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "second-object"?: any;
        "segment": { message: string; condition?: string; draggable?: boolean };
        "values": { [key: string]: string };
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SecondObjectComponent {
        "secondObject": { id: number; amount: number; status: 'proceed' | 'stop' | 'review'; reason: 'missing' | 'invalid' | 'duplicate' };
    }
}
export interface MessageSegmentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMessageSegmentElement;
}
declare global {
    interface HTMLFirstObjectComponentElement extends Components.FirstObjectComponent, HTMLStencilElement {
    }
    var HTMLFirstObjectComponentElement: {
        prototype: HTMLFirstObjectComponentElement;
        new (): HTMLFirstObjectComponentElement;
    };
    interface HTMLMainRenderElement extends Components.MainRender, HTMLStencilElement {
    }
    var HTMLMainRenderElement: {
        prototype: HTMLMainRenderElement;
        new (): HTMLMainRenderElement;
    };
    interface HTMLMessageSegmentElementEventMap {
        "segmentDragStart": number;
        "segmentDrop": { fromIndex: number; toIndex: number };
        "inputChange": { key: string; value: string };
    }
    interface HTMLMessageSegmentElement extends Components.MessageSegment, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMessageSegmentElementEventMap>(type: K, listener: (this: HTMLMessageSegmentElement, ev: MessageSegmentCustomEvent<HTMLMessageSegmentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMessageSegmentElementEventMap>(type: K, listener: (this: HTMLMessageSegmentElement, ev: MessageSegmentCustomEvent<HTMLMessageSegmentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMessageSegmentElement: {
        prototype: HTMLMessageSegmentElement;
        new (): HTMLMessageSegmentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSecondObjectComponentElement extends Components.SecondObjectComponent, HTMLStencilElement {
    }
    var HTMLSecondObjectComponentElement: {
        prototype: HTMLSecondObjectComponentElement;
        new (): HTMLSecondObjectComponentElement;
    };
    interface HTMLElementTagNameMap {
        "first-object-component": HTMLFirstObjectComponentElement;
        "main-render": HTMLMainRenderElement;
        "message-segment": HTMLMessageSegmentElement;
        "my-component": HTMLMyComponentElement;
        "second-object-component": HTMLSecondObjectComponentElement;
    }
}
declare namespace LocalJSX {
    interface FirstObjectComponent {
        "firstObject"?: { name: string; refId: number; type: 'claim' | 'normal' | 'promotion'; urgency: 'high' | 'medium' | 'low' };
    }
    interface MainRender {
    }
    interface MessageSegment {
        "firstObject"?: any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "first-object"?: any;
        "index"?: number;
        "onInputChange"?: (event: MessageSegmentCustomEvent<{ key: string; value: string }>) => void;
        "onSegmentDragStart"?: (event: MessageSegmentCustomEvent<number>) => void;
        "onSegmentDrop"?: (event: MessageSegmentCustomEvent<{ fromIndex: number; toIndex: number }>) => void;
        "secondObject"?: any;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "second-object"?: any;
        "segment"?: { message: string; condition?: string; draggable?: boolean };
        "values"?: { [key: string]: string };
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SecondObjectComponent {
        "secondObject"?: { id: number; amount: number; status: 'proceed' | 'stop' | 'review'; reason: 'missing' | 'invalid' | 'duplicate' };
    }
    interface IntrinsicElements {
        "first-object-component": FirstObjectComponent;
        "main-render": MainRender;
        "message-segment": MessageSegment;
        "my-component": MyComponent;
        "second-object-component": SecondObjectComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "first-object-component": LocalJSX.FirstObjectComponent & JSXBase.HTMLAttributes<HTMLFirstObjectComponentElement>;
            "main-render": LocalJSX.MainRender & JSXBase.HTMLAttributes<HTMLMainRenderElement>;
            "message-segment": LocalJSX.MessageSegment & JSXBase.HTMLAttributes<HTMLMessageSegmentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "second-object-component": LocalJSX.SecondObjectComponent & JSXBase.HTMLAttributes<HTMLSecondObjectComponentElement>;
        }
    }
}
